include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120
  trailing_commas: "preserve"

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_single_quotes: true
    prefer_relative_imports: true
    unnecessary_const: true
    prefer_const_declarations: true
    avoid_redundant_argument_values: true
